{% set name = "shared-memory38" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shared_memory38-{{ version }}.tar.gz
  sha256: 606f7e9247140ce5b18128f6749a7015e87bb3802c50302551545c82f9f649d2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py!=37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shared_memory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mars-project/shared_memory38
  summary: Backport of multiprocessing.shared_memory in Python 3.8
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
